# -*- coding: utf-8 -*-
"""Nihal Agriculture_Performace_Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nz-hdiqMJn1q_PPaKuc0aGwmRIj7tdmD

**Problem Statement: Seasonal Agriculture Performance Analysis**

Agricultural activities are influenced by seasonal variations in environmental conditions,
farming practices, resource availability and market conditions. As a result, agricultural
performance may differ from one season to another.

However, raw agricultural data does not clearly explain how agricultural performance changes
across seasons or what patterns can be observed in different seasonal conditions.

The problem is to analyze the given agricultural dataset and investigate seasonal differences
in agricultural performance by identifying meaningful patterns, trends, relationships and
variations within the available data.

**Questions**

1. How does agricultural performance vary across different seasons?
2. Which season has the highest agricultural performance?
3. Which season has the lowest agricultural performance?
4. What major seasonal patterns and trends can be observed in agricultural production?
5. Which agricultural characteristics change significantly between seasons?
6. How does resource usage vary across different seasons?
7. Is there a relationship between environmental conditions and agricultural performance?
8. How do economic outcomes differ between seasons?
9. Does agricultural performance vary across different regions during different seasons?
10. Are there any unusual or unexpected seasonal patterns in the dataset?
11. Which environmental or resource factor has the strongest relationship with agricultural performance?
12. Are seasonal patterns consistent across different regions or agricultural categories?
13. Are the differences in agricultural performance between seasons statistically significant?
14. What factors may contribute to higher or lower agricultural performance in particular seasons?
15.  How can the identified seasonal patterns support better agricultural planning?

**Data Wrangling:**

The agricultural dataset was inspected and prepared for analysis by checking the data structure, data types, missing values, duplicate records, inconsistent categorical values, and potential outliers. Column names were standardized, missing numerical values were handled using median imputation, and missing categorical values were handled using the mode. Categorical values were standardized to maintain consistency. The cleaned dataset was then validated and saved for further seasonal analysis.

1. Install & Import Libraries
"""

# Install required libraries
!pip install openpyxl seaborn scipy -q

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats
from google.colab import files

import warnings
warnings.filterwarnings("ignore")

# Plot settings
sns.set_theme(style="whitegrid")
plt.rcParams["figure.figsize"] = (10, 6)

"""2. Upload Dataset"""

uploaded = files.upload()

file_name = list(uploaded.keys())[0]

print("Uploaded file:", file_name)

if file_name.endswith(".csv"):
    df = pd.read_csv(file_name)

elif file_name.endswith(".xlsx") or file_name.endswith(".xls"):
    df = pd.read_excel(file_name)

else:
    print("Unsupported file format")

print("Dataset loaded successfully!")

print("First 5 Rows:")
display(df.head())

print("\nLast 5 Rows:")
display(df.tail())

print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

print("\nColumn Names:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

df.describe(include="all").T

missing_values = df.isnull().sum()

missing_table = pd.DataFrame({
    "Column": missing_values.index,
    "Missing Values": missing_values.values,
    "Missing %": (missing_values.values / len(df) * 100).round(2)
})

missing_table = missing_table.sort_values(
    by="Missing Values",
    ascending=False
)

display(missing_table)

duplicates = df.duplicated().sum()

print("Number of duplicate rows:", duplicates)

df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace(r"[^\w]", "", regex=True)
)

print(df.columns.tolist())

categorical_columns = df.select_dtypes(
    include=["object", "category"]
).columns.tolist()

numerical_columns = df.select_dtypes(
    include=np.number
).columns.tolist()

print("Categorical Columns:")
print(categorical_columns)

print("\nNumerical Columns:")
print(numerical_columns)

possible_season_columns = [
    col for col in df.columns
    if "season" in col.lower()
]

print("Possible Season Columns:")
print(possible_season_columns)

season_col = "season"

print(df[season_col].value_counts())

plt.figure(figsize=(10,6))

sns.countplot(
    data=df,
    x=season_col,
    order=df[season_col].value_counts().index
)

plt.title("Distribution of Agricultural Records Across Seasons")
plt.xlabel("Season")
plt.ylabel("Number of Records")
plt.xticks(rotation=45)

plt.show()

season_summary = df.groupby(season_col)[numerical_columns].mean()

display(season_summary)

for col in numerical_columns:

    plt.figure(figsize=(10,6))

    sns.boxplot(
        data=df,
        x=season_col,
        y=col
    )

    plt.title(f"{col.replace('_', ' ').title()} Across Seasons")
    plt.xlabel("Season")
    plt.ylabel(col.replace("_", " ").title())
    plt.xticks(rotation=45)

    plt.show()

possible_performance = [
    col for col in numerical_columns
    if any(word in col.lower()
           for word in ["yield", "production", "output", "profit", "revenue"])
]

print("Possible Performance Columns:")
print(possible_performance)

performance_col = "yield"

# Check your actual columns and automatically select performance column

print("Available columns:")
print(df.columns.tolist())

# Automatically find a suitable performance column
possible_columns = [
    "production",
    "crop_production",
    "productivity",
    "performance",
    "output",
    "harvest",
    "yield"
]

performance_col = next(
    (col for col in possible_columns if col in df.columns),
    None
)

# If none found, use the first numeric column
if performance_col is None:
    numeric_cols = df.select_dtypes(include="number").columns.tolist()
    performance_col = numeric_cols[0]

print("Using performance column:", performance_col)

# Your original analysis
season_performance = (
    df.groupby(season_col)[performance_col]
    .agg(["mean", "median", "min", "max", "std"])
    .sort_values("mean", ascending=False)
)

display(season_performance)

plt.figure(figsize=(10,6))

sns.barplot(
    data=df,
    x=season_col,
    y=performance_col,
    estimator="mean"
)

plt.title("Average Agricultural Performance by Season")
plt.xlabel("Season")
plt.ylabel("Average Performance")
plt.xticks(rotation=45)

plt.show()

best_season = season_performance["mean"].idxmax()
best_value = season_performance["mean"].max()

print("Best Performing Season:", best_season)
print("Average Performance:", round(best_value, 2))

worst_season = season_performance["mean"].idxmin()
worst_value = season_performance["mean"].min()

print("Lowest Performing Season:", worst_season)
print("Average Performance:", round(worst_value, 2))

resource_columns = [
    col for col in numerical_columns
    if any(word in col.lower()
           for word in [
               "water",
               "rain",
               "fertilizer",
               "fertiliser",
               "pesticide",
               "irrigation",
               "labor",
               "labour",
               "cost",
               "resource"
           ])
]

print("Possible Resource Columns:")
print(resource_columns)

for col in resource_columns:

    plt.figure(figsize=(10,6))

    sns.barplot(
        data=df,
        x=season_col,
        y=col,
        estimator="mean"
    )

    plt.title(f"Average {col.replace('_', ' ').title()} by Season")
    plt.xlabel("Season")
    plt.ylabel(col.replace("_", " ").title())
    plt.xticks(rotation=45)

    plt.show()

environment_columns = [
    col for col in numerical_columns
    if any(word in col.lower()
           for word in [
               "temperature",
               "humidity",
               "rainfall",
               "rain",
               "soil",
               "moisture",
               "sunlight",
               "weather",
               "pressure"
           ])
]

print("Environmental Columns:")
print(environment_columns)

if environment_columns:

    environment_summary = df.groupby(
        season_col
    )[environment_columns].mean()

    display(environment_summary)

correlation = df[numerical_columns].corr()

plt.figure(figsize=(14,10))

sns.heatmap(
    correlation,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Correlation Between Agricultural Variables")

plt.show()

performance_correlation = (
    correlation[performance_col]
    .sort_values(ascending=False)
)

display(performance_correlation)

if "rainfall" in df.columns:

    plt.figure(figsize=(10,6))

    sns.scatterplot(
        data=df,
        x="rainfall",
        y=performance_col,
        hue=season_col
    )

    plt.title("Rainfall vs Agricultural Performance")
    plt.xlabel("Rainfall")
    plt.ylabel("Agricultural Performance")

    plt.show()

for season in df[season_col].dropna().unique():

    season_data = df[df[season_col] == season]

    if len(season_data) > 2:

        corr = season_data[numerical_columns].corr()

        plt.figure(figsize=(12,8))

        sns.heatmap(
            corr,
            annot=True,
            cmap="coolwarm",
            fmt=".2f"
        )

        plt.title(f"Correlation Analysis — {season}")

        plt.show()

possible_region_columns = [
    col for col in df.columns
    if any(word in col.lower()
           for word in ["region", "area", "location", "district", "state"])
]

print(possible_region_columns)

region_col = "region"

# Automatically find the region/location column

region_candidates = [
    col for col in df.columns
    if any(word in col.lower()
           for word in ["region", "area", "location", "district", "state"])
]

if not region_candidates:
    print("Region column not found.")
    print("Available columns:")
    print(df.columns.tolist())
else:
    region_col = region_candidates[0]

    print("Using Region Column:", region_col)
    print("Using Season Column:", season_col)
    print("Using Performance Column:", performance_col)

    regional_analysis = pd.pivot_table(
        df,
        values=performance_col,
        index=region_col,
        columns=season_col,
        aggfunc="mean"
    )

    display(regional_analysis)

region_col = "region"

plt.figure(figsize=(12,8))

sns.heatmap(
    regional_analysis,
    annot=True,
    fmt=".2f",
    cmap="YlGn"
)

plt.title("Agricultural Performance by Region and Season")
plt.xlabel("Season")
plt.ylabel("Region")

plt.show()

groups = []

for season in df[season_col].dropna().unique():

    values = df.loc[
        df[season_col] == season,
        performance_col
    ].dropna()

    groups.append(values)

if len(groups) >= 2:

    anova_result = stats.f_oneway(*groups)

    print("ANOVA F-statistic:", round(anova_result.statistic, 4))
    print("ANOVA p-value:", round(anova_result.pvalue, 6))

alpha = 0.05

if anova_result.pvalue < alpha:
    print("Result: Significant difference exists between seasons.")
else:
    print("Result: No statistically significant difference detected.")

Q1 = df[performance_col].quantile(0.25)
Q3 = df[performance_col].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[
    (df[performance_col] < lower_bound) |
    (df[performance_col] > upper_bound)
]

print("Number of outliers:", len(outliers))

display(outliers.head(10))

top_records = df.sort_values(
    by=performance_col,
    ascending=False
).head(10)

display(top_records)

lowest_records = df.sort_values(
    by=performance_col,
    ascending=True
).head(10)

display(lowest_records)

print("=" * 60)
print("SEASONAL AGRICULTURE PERFORMANCE ANALYSIS")
print("=" * 60)

print("\nDataset Size:")
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

print("\nSeasons:")
print(df[season_col].unique())

print("\nBest Performing Season:")
print(best_season)

print("\nBest Average Performance:")
print(round(best_value, 2))

print("\nLowest Performing Season:")
print(worst_season)

print("\nLowest Average Performance:")
print(round(worst_value, 2))

season_means = df.groupby(season_col)[performance_col].mean()

best = season_means.idxmax()
worst = season_means.idxmin()

difference = season_means.max() - season_means.min()

print("KEY INSIGHTS")
print("-" * 50)

print(
    f"1. {best} recorded the highest average "
    f"{performance_col.replace('_', ' ')} "
    f"of {season_means.max():.2f}."
)

print(
    f"2. {worst} recorded the lowest average "
    f"{performance_col.replace('_', ' ')} "
    f"of {season_means.min():.2f}."
)

print(
    f"3. The difference between the highest and "
    f"lowest seasonal averages is {difference:.2f}."
)

print(
    f"4. The analysis contains "
    f"{df[season_col].nunique()} different seasons."
)

print(
    f"5. The dataset contains {len(df):,} agricultural records."
)

plt.figure(figsize=(12,7))

season_means.sort_values(ascending=False).plot(
    kind="bar"
)

plt.title("Seasonal Agricultural Performance")
plt.xlabel("Season")
plt.ylabel(f"Average {performance_col.replace('_', ' ').title()}")
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

output_file = "cleaned_agriculture_dataset.csv"

df.to_csv(
    output_file,
    index=False
)

print("Cleaned dataset saved as:", output_file)

files.download(output_file)

"""**Conclusion**

The Seasonal Agriculture Performance Analysis demonstrates that agricultural performance can vary across seasons due to differences in environmental conditions, farming practices, resource usage, and economic factors. The analysis helps identify the best and lowest-performing seasons, seasonal trends, variations in resource consumption, and relationships between environmental factors and agricultural outcomes.

Regional and seasonal comparisons provide a clearer understanding of how agricultural performance changes across different areas. Statistical analysis and visualizations further help determine whether observed seasonal differences are meaningful and identify unusual patterns.

Overall, the findings can support better seasonal agricultural planning by helping stakeholders allocate resources effectively, understand low-performing periods, and make data-driven decisions for improving agricultural productivity. This aligns with the project objective of identifying seasonal patterns, relationships, significant observations, and evidence-based recommendations.
"""